// Static fallback data for when the database is not available
// This allows the frontend to function during development without MariaDB

export const staticCategories = [
  { id: 1, name: 'อาหารแมว', slug: 'cat-food', description: 'อาหารแมวคุณภาพดี', image: '/assets/img/categories/cat-food.png', sortOrder: 1, isActive: true, _count: { products: 5 } },
  { id: 2, name: 'ขนมแมว', slug: 'cat-treats', description: 'ขนมแมว ขนมขบเคี้ยว', image: '/assets/img/categories/cat-treats.png', sortOrder: 2, isActive: true, _count: { products: 2 } },
  { id: 3, name: 'ทรายแมว', slug: 'cat-litter', description: 'ทรายแมวคุณภาพดี', image: '/assets/img/categories/cat-litter.png', sortOrder: 3, isActive: true, _count: { products: 2 } },
  { id: 4, name: 'ของเล่นแมว', slug: 'cat-toys', description: 'ของเล่นแมว หนูปลอม ลูกบอล', image: '/assets/img/categories/cat-toys.png', sortOrder: 4, isActive: true, _count: { products: 3 } },
  { id: 5, name: 'อุปกรณ์อาบน้ำ', slug: 'grooming', description: 'แชมพู ครีมอาบน้ำ แปรงหวี', image: '/assets/img/categories/grooming.png', sortOrder: 5, isActive: true, _count: { products: 3 } },
  { id: 6, name: 'ที่นอนแมว', slug: 'cat-beds', description: 'ที่นอนแมว เบาะแมว บ้านแมว', image: '/assets/img/categories/cat-beds.png', sortOrder: 6, isActive: true, _count: { products: 2 } },
  { id: 7, name: 'อุปกรณ์ให้อาหาร', slug: 'feeding', description: 'ชามอาหาร ที่ให้น้ำ', image: '/assets/img/categories/feeding.png', sortOrder: 7, isActive: true, _count: { products: 2 } },
];

export const staticProducts = [
  {
    id: 1, name: 'Royal Canin Indoor Adult อาหารแมวโต เลี้ยงในบ้าน', slug: 'royal-canin-indoor-adult',
    description: 'อาหารแมวโตที่เลี้ยงในบ้าน อายุ 1-7 ปี สูตรควบคุมน้ำหนัก ลดกลิ่นอุจจาระ',
    shortDesc: 'อาหารแมวโต เลี้ยงในบ้าน ควบคุมน้ำหนัก', sku: 'RC-IDA-2KG',
    price: '690', comparePrice: '790', stock: 50, weight: '2 kg', unit: 'ถุง',
    isFeatured: true, isActive: true, status: 'available', rating: '4.8', reviewCount: 156, salesCount: 320,
    tags: 'อาหารแมว,แมวโต,indoor,royal canin',
    category: { id: 1, name: 'อาหารแมว', slug: 'cat-food' },
    brand: { id: 1, name: 'Royal Canin', slug: 'royal-canin' },
    images: [
      { id: 1, url: '/assets/img/product-images/1_1.jpg', alt: 'Royal Canin Indoor', sortOrder: 0, isMain: true },
      { id: 2, url: '/assets/img/product-images/1_2.jpg', alt: 'Royal Canin Indoor', sortOrder: 1, isMain: false },
    ],
    variants: [
      { id: 1, name: 'ขนาด', value: '400 g', priceAdjust: '-490', stock: 30, sku: 'RC-IDA-400G', isActive: true },
      { id: 2, name: 'ขนาด', value: '2 kg', priceAdjust: '0', stock: 50, sku: 'RC-IDA-2KG', isActive: true },
      { id: 3, name: 'ขนาด', value: '4 kg', priceAdjust: '610', stock: 20, sku: 'RC-IDA-4KG', isActive: true },
    ],
  },
  {
    id: 2, name: 'Whiskas อาหารแมว รสปลาทู', slug: 'whiskas-mackerel',
    description: 'อาหารแมว Whiskas รสปลาทู สูตรครบถ้วนสำหรับแมวโต',
    shortDesc: 'อาหารแมว Whiskas รสปลาทู สูตรครบถ้วน', sku: 'WK-MCK-3KG',
    price: '299', comparePrice: '350', stock: 100, weight: '3 kg', unit: 'ถุง',
    isFeatured: true, isActive: true, status: 'available', rating: '4.5', reviewCount: 230, salesCount: 550,
    tags: 'อาหารแมว,whiskas,ปลาทู',
    category: { id: 1, name: 'อาหารแมว', slug: 'cat-food' },
    brand: { id: 2, name: 'Whiskas', slug: 'whiskas' },
    images: [
      { id: 3, url: '/assets/img/product-images/2_1.jpg', alt: 'Whiskas Mackerel', sortOrder: 0, isMain: true },
    ],
    variants: [],
  },
  {
    id: 3, name: 'Me-O อาหารแมว รสทูน่า', slug: 'meo-tuna',
    description: 'อาหารแมว Me-O รสทูน่า โปรตีนสูงจากเนื้อปลาทูน่า',
    shortDesc: 'อาหารแมว Me-O รสทูน่า โปรตีนสูง', sku: 'MO-TN-1.2KG',
    price: '185', comparePrice: '220', stock: 80, weight: '1.2 kg', unit: 'ถุง',
    isFeatured: false, isActive: true, status: 'available', rating: '4.3', reviewCount: 89, salesCount: 200,
    tags: 'อาหารแมว,meo,ทูน่า',
    category: { id: 1, name: 'อาหารแมว', slug: 'cat-food' },
    brand: { id: 3, name: 'Me-O', slug: 'me-o' },
    images: [
      { id: 5, url: '/assets/img/product-images/3_1.jpg', alt: 'Me-O Tuna', sortOrder: 0, isMain: true },
    ],
    variants: [],
  },
  {
    id: 4, name: 'Royal Canin Kitten อาหารลูกแมว', slug: 'royal-canin-kitten',
    description: 'อาหารลูกแมว Royal Canin สูตรเสริมภูมิคุ้มกัน',
    shortDesc: 'อาหารลูกแมว เสริมภูมิคุ้มกัน', sku: 'RC-KIT-2KG',
    price: '750', comparePrice: '850', stock: 35, weight: '2 kg', unit: 'ถุง',
    isFeatured: true, isActive: true, status: 'available', rating: '4.9', reviewCount: 198, salesCount: 410,
    tags: 'อาหารแมว,ลูกแมว,kitten,royal canin',
    category: { id: 1, name: 'อาหารแมว', slug: 'cat-food' },
    brand: { id: 1, name: 'Royal Canin', slug: 'royal-canin' },
    images: [
      { id: 7, url: '/assets/img/product-images/4_1.jpg', alt: 'Royal Canin Kitten', sortOrder: 0, isMain: true },
    ],
    variants: [],
  },
  {
    id: 5, name: 'Me-O Creamy Treats ขนมแมวเลีย รสทูน่า', slug: 'meo-creamy-tuna',
    description: 'ขนมแมวเลีย Me-O Creamy Treats รสทูน่า แพ็ค 4 ซอง',
    shortDesc: 'ขนมแมวเลีย รสทูน่า 4 ซอง', sku: 'MO-CRM-TN-4P',
    price: '35', comparePrice: '45', stock: 200, weight: '60 g', unit: 'แพ็ค',
    isFeatured: true, isActive: true, status: 'available', rating: '4.7', reviewCount: 340, salesCount: 890,
    tags: 'ขนมแมว,ขนมแมวเลีย,ทูน่า,meo',
    category: { id: 2, name: 'ขนมแมว', slug: 'cat-treats' },
    brand: { id: 3, name: 'Me-O', slug: 'me-o' },
    images: [
      { id: 9, url: '/assets/img/product-images/5_1.jpg', alt: 'Me-O Creamy', sortOrder: 0, isMain: true },
    ],
    variants: [],
  },
  {
    id: 6, name: 'Kit Cat Purr Puree ขนมแมวเลีย รสไก่', slug: 'kitcat-purr-puree-chicken',
    description: 'ขนมแมวเลีย Kit Cat Purr Puree รสไก่ จากเนื้อไก่แท้',
    shortDesc: 'ขนมแมวเลีย รสไก่ จากเนื้อไก่แท้', sku: 'KC-PP-CK-4P',
    price: '49', comparePrice: '59', stock: 150, weight: '60 g', unit: 'แพ็ค',
    isFeatured: false, isActive: true, status: 'available', rating: '4.6', reviewCount: 220, salesCount: 670,
    tags: 'ขนมแมว,ขนมแมวเลีย,ไก่,kit cat',
    category: { id: 2, name: 'ขนมแมว', slug: 'cat-treats' },
    brand: { id: 4, name: 'Kit Cat', slug: 'kit-cat' },
    images: [
      { id: 11, url: '/assets/img/product-images/6_1.jpg', alt: 'Kit Cat Purr Puree', sortOrder: 0, isMain: true },
    ],
    variants: [],
  },
  {
    id: 7, name: 'Kit Cat Soybean Litter ทรายแมวเต้าหู้', slug: 'kitcat-soybean-litter',
    description: 'ทรายแมวเต้าหู้ Kit Cat ผลิตจากกากถั่วเหลือง ธรรมชาติ 100%',
    shortDesc: 'ทรายแมวเต้าหู้ ธรรมชาติ ทิ้งลงชักโครกได้', sku: 'KC-SBL-7L',
    price: '199', comparePrice: '250', stock: 60, weight: '7 L', unit: 'ถุง',
    isFeatured: true, isActive: true, status: 'available', rating: '4.6', reviewCount: 180, salesCount: 450,
    tags: 'ทรายแมว,เต้าหู้,kit cat,ธรรมชาติ',
    category: { id: 3, name: 'ทรายแมว', slug: 'cat-litter' },
    brand: { id: 4, name: 'Kit Cat', slug: 'kit-cat' },
    images: [
      { id: 13, url: '/assets/img/product-images/7_1.jpg', alt: 'Kit Cat Soybean', sortOrder: 0, isMain: true },
    ],
    variants: [
      { id: 4, name: 'กลิ่น', value: 'ไม่มีกลิ่น', priceAdjust: '0', stock: 20, isActive: true },
      { id: 5, name: 'กลิ่น', value: 'ชาเขียว', priceAdjust: '10', stock: 15, isActive: true },
      { id: 6, name: 'กลิ่น', value: 'ลาเวนเดอร์', priceAdjust: '10', stock: 15, isActive: true },
    ],
  },
  {
    id: 8, name: 'Purrfect ทรายแมวภูเขาไฟ กลิ่นลาเวนเดอร์', slug: 'purrfect-bentonite-lavender',
    description: 'ทรายแมวภูเขาไฟ Purrfect กลิ่นลาเวนเดอร์ จับก้อนเร็ว',
    shortDesc: 'ทรายแมวภูเขาไฟ กลิ่นลาเวนเดอร์ ฝุ่นน้อย', sku: 'PF-BNT-LV-10L',
    price: '159', comparePrice: '199', stock: 40, weight: '10 L', unit: 'ถุง',
    isFeatured: false, isActive: true, status: 'available', rating: '4.4', reviewCount: 95, salesCount: 280,
    tags: 'ทรายแมว,ภูเขาไฟ,ลาเวนเดอร์',
    category: { id: 3, name: 'ทรายแมว', slug: 'cat-litter' },
    brand: { id: 6, name: 'Purrfect', slug: 'purrfect' },
    images: [
      { id: 15, url: '/assets/img/product-images/8_1.jpg', alt: 'Purrfect Bentonite', sortOrder: 0, isMain: true },
    ],
    variants: [],
  },
  {
    id: 9, name: 'Catit ลวดล่อแมว พร้อมขนนก', slug: 'catit-feather-teaser',
    description: 'ลวดล่อแมว Catit มาพร้อมขนนกสีสันสดใส กระตุ้นสัญชาตญาณการล่า',
    shortDesc: 'ลวดล่อแมว พร้อมขนนก ด้ามจับถนัดมือ', sku: 'CT-FTR-01',
    price: '129', comparePrice: '159', stock: 70, weight: '50 g', unit: 'ชิ้น',
    isFeatured: false, isActive: true, status: 'available', rating: '4.5', reviewCount: 120, salesCount: 340,
    tags: 'ของเล่นแมว,ลวดล่อแมว,ขนนก,catit',
    category: { id: 4, name: 'ของเล่นแมว', slug: 'cat-toys' },
    brand: { id: 5, name: 'Catit', slug: 'catit' },
    images: [
      { id: 17, url: '/assets/img/product-images/9_1.jpg', alt: 'Catit Feather Teaser', sortOrder: 0, isMain: true },
    ],
    variants: [],
  },
  {
    id: 10, name: 'MeePro หนูของเล่น แคทนิป 3 ตัว', slug: 'meepro-catnip-mouse-3pack',
    description: 'หนูของเล่นแมว MeePro บรรจุแคทนิปภายใน แมวชอบมาก!',
    shortDesc: 'หนูของเล่นแมว แคทนิป แพ็ค 3 ตัว', sku: 'MP-MSE-3P',
    price: '89', comparePrice: '120', stock: 120, weight: '30 g', unit: 'แพ็ค',
    isFeatured: true, isActive: true, status: 'available', rating: '4.7', reviewCount: 88, salesCount: 230,
    tags: 'ของเล่นแมว,หนูของเล่น,แคทนิป,meepro',
    category: { id: 4, name: 'ของเล่นแมว', slug: 'cat-toys' },
    brand: { id: 7, name: 'MeePro', slug: 'meepro' },
    images: [
      { id: 19, url: '/assets/img/product-images/10_1.jpg', alt: 'MeePro Catnip Mouse', sortOrder: 0, isMain: true },
    ],
    variants: [],
  },
  {
    id: 11, name: 'Catit ลูกบอลกระดิ่ง ของเล่นแมว 4 ลูก', slug: 'catit-jingle-ball-4pack',
    description: 'ลูกบอลกระดิ่งสำหรับแมว Catit แพ็ค 4 ลูก สีสันสดใส',
    shortDesc: 'ลูกบอลกระดิ่ง ของเล่นแมว 4 ลูก', sku: 'CT-JBL-4P',
    price: '79', comparePrice: '99', stock: 90, weight: '80 g', unit: 'แพ็ค',
    isFeatured: false, isActive: true, status: 'available', rating: '4.3', reviewCount: 65, salesCount: 160,
    tags: 'ของเล่นแมว,ลูกบอล,กระดิ่ง,catit',
    category: { id: 4, name: 'ของเล่นแมว', slug: 'cat-toys' },
    brand: { id: 5, name: 'Catit', slug: 'catit' },
    images: [
      { id: 21, url: '/assets/img/product-images/11_1.jpg', alt: 'Catit Jingle Ball', sortOrder: 0, isMain: true },
    ],
    variants: [],
  },
  {
    id: 12, name: 'MeePro แชมพูแมว สูตรอ่อนโยน กลิ่นดอกไม้', slug: 'meepro-cat-shampoo-floral',
    description: 'แชมพูแมว MeePro สูตรอ่อนโยน กลิ่นดอกไม้ ผลิตจากสารสกัดธรรมชาติ',
    shortDesc: 'แชมพูแมว สูตรอ่อนโยน กลิ่นดอกไม้', sku: 'MP-SHP-FL-500',
    price: '189', comparePrice: '249', stock: 45, weight: '500 ml', unit: 'ขวด',
    isFeatured: true, isActive: true, status: 'available', rating: '4.8', reviewCount: 135, salesCount: 380,
    tags: 'แชมพูแมว,อาบน้ำแมว,ดอกไม้,meepro',
    category: { id: 5, name: 'อุปกรณ์อาบน้ำ', slug: 'grooming' },
    brand: { id: 7, name: 'MeePro', slug: 'meepro' },
    images: [
      { id: 23, url: '/assets/img/product-images/12_1.jpg', alt: 'MeePro Shampoo', sortOrder: 0, isMain: true },
    ],
    variants: [],
  },
  {
    id: 13, name: 'Purrfect ครีมนวดขนแมว สูตรขนนุ่ม', slug: 'purrfect-conditioner-soft',
    description: 'ครีมนวดขนแมว Purrfect สูตรขนนุ่ม ลดขนพันกัน',
    shortDesc: 'ครีมนวดขนแมว สูตรขนนุ่ม ลดขนพันกัน', sku: 'PF-CND-ST-300',
    price: '169', comparePrice: '220', stock: 30, weight: '300 ml', unit: 'ขวด',
    isFeatured: false, isActive: true, status: 'available', rating: '4.5', reviewCount: 72, salesCount: 190,
    tags: 'ครีมนวดขน,แมว,ขนนุ่ม,purrfect',
    category: { id: 5, name: 'อุปกรณ์อาบน้ำ', slug: 'grooming' },
    brand: { id: 6, name: 'Purrfect', slug: 'purrfect' },
    images: [
      { id: 25, url: '/assets/img/product-images/13_1.jpg', alt: 'Purrfect Conditioner', sortOrder: 0, isMain: true },
    ],
    variants: [],
  },
  {
    id: 14, name: 'MeePro เบาะนอนแมว ทรงกลม ขนนุ่ม', slug: 'meepro-round-bed-fluffy',
    description: 'เบาะนอนแมว MeePro ทรงกลม ขนปุยนุ่ม ซักเครื่องได้',
    shortDesc: 'เบาะนอนแมว ทรงกลม ขนนุ่มปุย', sku: 'MP-BED-RD-50',
    price: '390', comparePrice: '490', stock: 25, weight: '500 g', unit: 'ชิ้น',
    isFeatured: true, isActive: true, status: 'available', rating: '4.9', reviewCount: 210, salesCount: 520,
    tags: 'ที่นอนแมว,เบาะแมว,ขนนุ่ม,meepro',
    category: { id: 6, name: 'ที่นอนแมว', slug: 'cat-beds' },
    brand: { id: 7, name: 'MeePro', slug: 'meepro' },
    images: [
      { id: 27, url: '/assets/img/product-images/14_1.jpg', alt: 'MeePro Round Bed', sortOrder: 0, isMain: true },
    ],
    variants: [
      { id: 7, name: 'สี', value: 'เทา', priceAdjust: '0', stock: 10, isActive: true },
      { id: 8, name: 'สี', value: 'ครีม', priceAdjust: '0', stock: 8, isActive: true },
      { id: 9, name: 'สี', value: 'ชมพู', priceAdjust: '0', stock: 7, isActive: true },
    ],
  },
  {
    id: 15, name: 'Catit Vesper คอนโดแมว 3 ชั้น', slug: 'catit-vesper-condo-3tier',
    description: 'คอนโดแมว Catit Vesper 3 ชั้น มีเสาลับเล็บ ไม้แท้คุณภาพดี',
    shortDesc: 'คอนโดแมว 3 ชั้น มีเสาลับเล็บ', sku: 'CT-VSP-3T',
    price: '2490', comparePrice: '2990', stock: 10, weight: '8 kg', unit: 'ชิ้น',
    isFeatured: false, isActive: true, status: 'available', rating: '4.7', reviewCount: 45, salesCount: 65,
    tags: 'คอนโดแมว,เสาลับเล็บ,catit,vesper',
    category: { id: 6, name: 'ที่นอนแมว', slug: 'cat-beds' },
    brand: { id: 5, name: 'Catit', slug: 'catit' },
    images: [
      { id: 29, url: '/assets/img/product-images/15_1.jpg', alt: 'Catit Vesper Condo', sortOrder: 0, isMain: true },
    ],
    variants: [],
  },
  {
    id: 16, name: 'Catit Pixi น้ำพุแมว สแตนเลส', slug: 'catit-pixi-fountain',
    description: 'น้ำพุแมว Catit Pixi สแตนเลส 2.5 ลิตร ระบบกรองน้ำ 3 ชั้น',
    shortDesc: 'น้ำพุแมว สแตนเลส 2.5 ลิตร ระบบกรอง 3 ชั้น', sku: 'CT-PXF-SS-25',
    price: '1290', comparePrice: '1590', stock: 15, weight: '1.2 kg', unit: 'ชิ้น',
    isFeatured: true, isActive: true, status: 'available', rating: '4.8', reviewCount: 95, salesCount: 180,
    tags: 'น้ำพุแมว,สแตนเลส,catit,pixi',
    category: { id: 7, name: 'อุปกรณ์ให้อาหาร', slug: 'feeding' },
    brand: { id: 5, name: 'Catit', slug: 'catit' },
    images: [
      { id: 31, url: '/assets/img/product-images/16_1.jpg', alt: 'Catit Pixi Fountain', sortOrder: 0, isMain: true },
    ],
    variants: [],
  },
  {
    id: 17, name: 'MeePro ชามอาหารแมว เซรามิก ยกสูง', slug: 'meepro-ceramic-bowl-raised',
    description: 'ชามอาหารแมว MeePro เซรามิก ยกสูง 15 องศา ช่วยลดอาการอาเจียน',
    shortDesc: 'ชามอาหารแมว เซรามิก ยกสูง ลดอาเจียน', sku: 'MP-BWL-CR-RD',
    price: '249', comparePrice: '320', stock: 40, weight: '400 g', unit: 'ชิ้น',
    isFeatured: false, isActive: true, status: 'available', rating: '4.6', reviewCount: 75, salesCount: 200,
    tags: 'ชามอาหาร,เซรามิก,ยกสูง,meepro',
    category: { id: 7, name: 'อุปกรณ์ให้อาหาร', slug: 'feeding' },
    brand: { id: 7, name: 'MeePro', slug: 'meepro' },
    images: [
      { id: 33, url: '/assets/img/product-images/17_1.jpg', alt: 'MeePro Ceramic Bowl', sortOrder: 0, isMain: true },
    ],
    variants: [],
  },
  {
    id: 18, name: 'MeePro แปรงหวีขนแมว สลิคเกอร์', slug: 'meepro-slicker-brush',
    description: 'แปรงหวีขนแมว MeePro แบบสลิคเกอร์ ช่วยรวบขนที่หลุดร่วง',
    shortDesc: 'แปรงหวีขนแมว สลิคเกอร์ ลดขนร่วง', sku: 'MP-BRS-SLK',
    price: '119', comparePrice: '150', stock: 55, weight: '100 g', unit: 'ชิ้น',
    isFeatured: false, isActive: true, status: 'available', rating: '4.3', reviewCount: 42, salesCount: 110,
    tags: 'แปรงหวีขน,แมว,สลิคเกอร์,meepro',
    category: { id: 5, name: 'อุปกรณ์อาบน้ำ', slug: 'grooming' },
    brand: { id: 7, name: 'MeePro', slug: 'meepro' },
    images: [
      { id: 35, url: '/assets/img/product-images/18_1.jpg', alt: 'MeePro Slicker Brush', sortOrder: 0, isMain: true },
    ],
    variants: [],
  },
];

export const staticBanners = [
  { id: 1, title: 'อาหารแมวคุณภาพ ลดสูงสุด 30%', subtitle: 'Royal Canin, Whiskas, Me-O และอีกมากมาย', image: '/assets/img/banners/banner-1.jpg', link: '/shop?category=cat-food', sortOrder: 1, isActive: true },
  { id: 2, title: 'ของเล่นแมว มาใหม่!', subtitle: 'ลวดล่อแมว หนูแคทนิป ลูกบอล สนุกสนานทั้งวัน', image: '/assets/img/banners/banner-2.jpg', link: '/shop?category=cat-toys', sortOrder: 2, isActive: true },
  { id: 3, title: 'ทรายแมวเต้าหู้ ธรรมชาติ 100%', subtitle: 'ปลอดภัย ทิ้งลงชักโครกได้ จับก้อนดี', image: '/assets/img/banners/banner-3.jpg', link: '/shop?category=cat-litter', sortOrder: 3, isActive: true },
];
