services:
  mariadb:
    image: mariadb:11
    container_name: meepro-mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "pwD@20200"
      MARIADB_DATABASE: meepro_petshop
      MARIADB_CHARACTER_SET: utf8mb4
      MARIADB_COLLATION: utf8mb4_unicode_ci
    volumes:
      - meepro_db_data:/var/lib/mysql

volumes:
  meepro_db_data:
